// Code generated by simdjsongen; DO NOT EDIT.

package gentest

import (
	"strings"

	simdjson "github.com/thesyncim/simdjson"
)

var _ = strings.EqualFold

// DocumentJSONDecoder is a concrete generated decoder for Document.
type DocumentJSONDecoder struct {
	Options simdjson.TypedOptions
}

func (decoder DocumentJSONDecoder) Decode(src []byte, dst *Document) error {
	if dst == nil {
		return &simdjson.TypedDecodeError{TypeName: "Document", Reason: "destination is nil"}
	}
	cursor := simdjson.NewDecoderCursor(src, decoder.Options)
	if err := simdjsonDecodeDocument(&cursor, dst); err != nil {
		return err
	}
	return cursor.Finish()
}

func (decoder DocumentJSONDecoder) DecodeArray(src []byte, dst []Document) ([]Document, error) {
	cursor := simdjson.NewDecoderCursor(src, decoder.Options)
	null, err := cursor.TryNull()
	if err != nil {
		return dst, err
	}
	if null {
		return nil, cursor.Finish()
	}
	if err := cursor.BeginArray("[]Document"); err != nil {
		return dst, err
	}
	if dst == nil {
		dst = make([]Document, 0)
	}
	dst = dst[:0]
	for first := true; ; first = false {
		more, err := cursor.NextArrayElement(first)
		if err != nil {
			return dst, err
		}
		if !more {
			break
		}
		if first {
			cursor.ReserveSlice(&dst, 128)
		}
		index := len(dst)
		if index < cap(dst) {
			dst = dst[:index+1]
		} else {
			var zero Document
			dst = append(dst, zero)
		}
		if err := simdjsonDecodeDocument(&cursor, &dst[index]); err != nil {
			return dst, err
		}
	}
	return dst, cursor.Finish()
}

// NumericJSONDecoder is a concrete generated decoder for Numeric.
type NumericJSONDecoder struct {
	Options simdjson.TypedOptions
}

func (decoder NumericJSONDecoder) Decode(src []byte, dst *Numeric) error {
	if dst == nil {
		return &simdjson.TypedDecodeError{TypeName: "Numeric", Reason: "destination is nil"}
	}
	cursor := simdjson.NewDecoderCursor(src, decoder.Options)
	if err := simdjsonDecodeNumeric(&cursor, dst); err != nil {
		return err
	}
	return cursor.Finish()
}

func (decoder NumericJSONDecoder) DecodeArray(src []byte, dst []Numeric) ([]Numeric, error) {
	cursor := simdjson.NewDecoderCursor(src, decoder.Options)
	null, err := cursor.TryNull()
	if err != nil {
		return dst, err
	}
	if null {
		return nil, cursor.Finish()
	}
	if err := cursor.BeginArray("[]Numeric"); err != nil {
		return dst, err
	}
	if dst == nil {
		dst = make([]Numeric, 0)
	}
	dst = dst[:0]
	for first := true; ; first = false {
		more, err := cursor.NextArrayElement(first)
		if err != nil {
			return dst, err
		}
		if !more {
			break
		}
		if first {
			cursor.ReserveSlice(&dst, 128)
		}
		index := len(dst)
		if index < cap(dst) {
			dst = dst[:index+1]
		} else {
			var zero Numeric
			dst = append(dst, zero)
		}
		if err := simdjsonDecodeNumeric(&cursor, &dst[index]); err != nil {
			return dst, err
		}
	}
	return dst, cursor.Finish()
}

func simdjsonResetDocument(dst *Document) {
	dst.Items = dst.Items[:0]
	simdjsonResetMeta(&dst.Meta)
	dst.Optional = nil
	var zero1 [2]int
	dst.Fixed = zero1
}

func simdjsonDecodeDocument(cursor *simdjson.DecoderCursor, dst *Document) error {
	null, err := cursor.TryNull()
	if err != nil {
		return err
	}
	simdjsonResetDocument(dst)
	if null {
		return nil
	}
	if err := cursor.BeginObject("Document"); err != nil {
		return err
	}
	for first := true; ; first = false {
		key, ok, err := cursor.NextObjectField(first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "items":
			goto simdjsonField0
		case "meta":
			goto simdjsonField1
		case "optional":
			goto simdjsonField2
		case "fixed":
			goto simdjsonField3
		default:
			if !cursor.CaseSensitive() {
				if strings.EqualFold(key, "items") {
					goto simdjsonField0
				}
				if strings.EqualFold(key, "meta") {
					goto simdjsonField1
				}
				if strings.EqualFold(key, "optional") {
					goto simdjsonField2
				}
				if strings.EqualFold(key, "fixed") {
					goto simdjsonField3
				}
			}
			if err := cursor.Unknown("Document", key); err != nil {
				return err
			}
			continue
		}
	simdjsonField0:
		{
			null2, err2 := cursor.TryNull()
			if err2 != nil {
				return err2
			}
			if null2 {
				dst.Items = nil
			} else {
				if err := cursor.BeginArray("[]Record"); err != nil {
					return err
				}
				if dst.Items == nil {
					dst.Items = make([]Record, 0)
				}
				dst.Items = dst.Items[:0]
				for first2 := true; ; first2 = false {
					more2, err2 := cursor.NextArrayElement(first2)
					if err2 != nil {
						return err2
					}
					if !more2 {
						break
					}
					if first2 {
						cursor.ReserveSlice(&dst.Items, 128)
					}
					index2 := len(dst.Items)
					if index2 < cap(dst.Items) {
						dst.Items = dst.Items[:index2+1]
					} else {
						var zero2 Record
						dst.Items = append(dst.Items, zero2)
					}
					if err := simdjsonDecodeRecord(cursor, &dst.Items[index2]); err != nil {
						return err
					}
				}
			}
		}
		continue
	simdjsonField1:
		{
			if err := simdjsonDecodeMeta(cursor, &dst.Meta); err != nil {
				return err
			}
		}
		continue
	simdjsonField2:
		{
			null3, err3 := cursor.TryNull()
			if err3 != nil {
				return err3
			}
			if null3 {
				dst.Optional = nil
			} else {
				if dst.Optional == nil {
					dst.Optional = new(Meta)
				}
				if err := simdjsonDecodeMeta(cursor, &*(dst.Optional)); err != nil {
					return err
				}
			}
		}
		continue
	simdjsonField3:
		{
			null4, err4 := cursor.TryNull()
			if err4 != nil {
				return err4
			}
			var zero4 [2]int
			dst.Fixed = zero4
			if !null4 {
				if err := cursor.BeginArray("[2]int"); err != nil {
					return err
				}
				for index4, first4 := 0, true; ; index4, first4 = index4+1, false {
					more4, err4 := cursor.NextArrayElement(first4)
					if err4 != nil {
						return err4
					}
					if !more4 {
						break
					}
					if index4 < len(dst.Fixed) {
						if err := cursor.Int(&dst.Fixed[index4]); err != nil {
							return err
						}
					} else if err := cursor.Skip(); err != nil {
						return err
					}
				}
			}
		}
		continue
	}
}

func simdjsonResetMeta(dst *Meta) {
	var zero5 uint
	dst.Count = zero5
	var zero6 string
	dst.Source = zero6
}

func simdjsonDecodeMeta(cursor *simdjson.DecoderCursor, dst *Meta) error {
	null, err := cursor.TryNull()
	if err != nil {
		return err
	}
	simdjsonResetMeta(dst)
	if null {
		return nil
	}
	if err := cursor.BeginObject("Meta"); err != nil {
		return err
	}
	for first := true; ; first = false {
		key, ok, err := cursor.NextObjectField(first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "count":
			goto simdjsonField0
		case "source":
			goto simdjsonField1
		default:
			if !cursor.CaseSensitive() {
				if strings.EqualFold(key, "count") {
					goto simdjsonField0
				}
				if strings.EqualFold(key, "source") {
					goto simdjsonField1
				}
			}
			if err := cursor.Unknown("Meta", key); err != nil {
				return err
			}
			continue
		}
	simdjsonField0:
		{
			if err := cursor.Uint(&dst.Count); err != nil {
				return err
			}
		}
		continue
	simdjsonField1:
		{
			if err := cursor.String(&dst.Source); err != nil {
				return err
			}
		}
		continue
	}
}

func simdjsonResetNumeric(dst *Numeric) {
	var zero7 int8
	dst.I8 = zero7
	var zero8 int16
	dst.I16 = zero8
	var zero9 int32
	dst.I32 = zero9
	var zero10 int64
	dst.I64 = zero10
	var zero11 int
	dst.Int = zero11
	var zero12 uint8
	dst.U8 = zero12
	var zero13 uint16
	dst.U16 = zero13
	var zero14 uint32
	dst.U32 = zero14
	var zero15 uint64
	dst.U64 = zero15
	var zero16 uint
	dst.Uint = zero16
	var zero17 float32
	dst.F32 = zero17
	var zero18 float64
	dst.F64 = zero18
	var zero19 bool
	dst.Bool = zero19
	var zero20 string
	dst.Text = zero20
	dst.Number = ""
}

func simdjsonDecodeNumeric(cursor *simdjson.DecoderCursor, dst *Numeric) error {
	null, err := cursor.TryNull()
	if err != nil {
		return err
	}
	simdjsonResetNumeric(dst)
	if null {
		return nil
	}
	if err := cursor.BeginObject("Numeric"); err != nil {
		return err
	}
	for first := true; ; first = false {
		key, ok, err := cursor.NextObjectField(first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "i8":
			goto simdjsonField0
		case "i16":
			goto simdjsonField1
		case "i32":
			goto simdjsonField2
		case "i64":
			goto simdjsonField3
		case "int":
			goto simdjsonField4
		case "u8":
			goto simdjsonField5
		case "u16":
			goto simdjsonField6
		case "u32":
			goto simdjsonField7
		case "u64":
			goto simdjsonField8
		case "uint":
			goto simdjsonField9
		case "f32":
			goto simdjsonField10
		case "f64":
			goto simdjsonField11
		case "bool":
			goto simdjsonField12
		case "text":
			goto simdjsonField13
		case "number":
			goto simdjsonField14
		default:
			if !cursor.CaseSensitive() {
				if strings.EqualFold(key, "i8") {
					goto simdjsonField0
				}
				if strings.EqualFold(key, "i16") {
					goto simdjsonField1
				}
				if strings.EqualFold(key, "i32") {
					goto simdjsonField2
				}
				if strings.EqualFold(key, "i64") {
					goto simdjsonField3
				}
				if strings.EqualFold(key, "int") {
					goto simdjsonField4
				}
				if strings.EqualFold(key, "u8") {
					goto simdjsonField5
				}
				if strings.EqualFold(key, "u16") {
					goto simdjsonField6
				}
				if strings.EqualFold(key, "u32") {
					goto simdjsonField7
				}
				if strings.EqualFold(key, "u64") {
					goto simdjsonField8
				}
				if strings.EqualFold(key, "uint") {
					goto simdjsonField9
				}
				if strings.EqualFold(key, "f32") {
					goto simdjsonField10
				}
				if strings.EqualFold(key, "f64") {
					goto simdjsonField11
				}
				if strings.EqualFold(key, "bool") {
					goto simdjsonField12
				}
				if strings.EqualFold(key, "text") {
					goto simdjsonField13
				}
				if strings.EqualFold(key, "number") {
					goto simdjsonField14
				}
			}
			if err := cursor.Unknown("Numeric", key); err != nil {
				return err
			}
			continue
		}
	simdjsonField0:
		{
			if err := cursor.Int(&dst.I8); err != nil {
				return err
			}
		}
		continue
	simdjsonField1:
		{
			if err := cursor.Int(&dst.I16); err != nil {
				return err
			}
		}
		continue
	simdjsonField2:
		{
			if err := cursor.Int(&dst.I32); err != nil {
				return err
			}
		}
		continue
	simdjsonField3:
		{
			if err := cursor.Int(&dst.I64); err != nil {
				return err
			}
		}
		continue
	simdjsonField4:
		{
			if err := cursor.Int(&dst.Int); err != nil {
				return err
			}
		}
		continue
	simdjsonField5:
		{
			if err := cursor.Uint(&dst.U8); err != nil {
				return err
			}
		}
		continue
	simdjsonField6:
		{
			if err := cursor.Uint(&dst.U16); err != nil {
				return err
			}
		}
		continue
	simdjsonField7:
		{
			if err := cursor.Uint(&dst.U32); err != nil {
				return err
			}
		}
		continue
	simdjsonField8:
		{
			if err := cursor.Uint(&dst.U64); err != nil {
				return err
			}
		}
		continue
	simdjsonField9:
		{
			if err := cursor.Uint(&dst.Uint); err != nil {
				return err
			}
		}
		continue
	simdjsonField10:
		{
			if err := cursor.Float(&dst.F32); err != nil {
				return err
			}
		}
		continue
	simdjsonField11:
		{
			if err := cursor.Float(&dst.F64); err != nil {
				return err
			}
		}
		continue
	simdjsonField12:
		{
			if err := cursor.Bool(&dst.Bool); err != nil {
				return err
			}
		}
		continue
	simdjsonField13:
		{
			if err := cursor.String(&dst.Text); err != nil {
				return err
			}
		}
		continue
	simdjsonField14:
		{
			if err := cursor.Number(&dst.Number); err != nil {
				return err
			}
		}
		continue
	}
}

func simdjsonResetRecord(dst *Record) {
	var zero21 int
	dst.ID = zero21
	var zero22 bool
	dst.Active = zero22
	var zero23 string
	dst.Name = zero23
	var zero24 string
	dst.Message = zero24
	var zero25 [3]Score
	dst.Scores = zero25
	dst.Number = ""
}

func simdjsonDecodeRecord(cursor *simdjson.DecoderCursor, dst *Record) error {
	null, err := cursor.TryNull()
	if err != nil {
		return err
	}
	simdjsonResetRecord(dst)
	if null {
		return nil
	}
	if err := cursor.BeginObject("Record"); err != nil {
		return err
	}
	for first := true; ; first = false {
		key, ok, err := cursor.NextObjectField(first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "id":
			goto simdjsonField0
		case "active":
			goto simdjsonField1
		case "name":
			goto simdjsonField2
		case "message":
			goto simdjsonField3
		case "scores":
			goto simdjsonField4
		case "number":
			goto simdjsonField5
		default:
			if !cursor.CaseSensitive() {
				if strings.EqualFold(key, "id") {
					goto simdjsonField0
				}
				if strings.EqualFold(key, "active") {
					goto simdjsonField1
				}
				if strings.EqualFold(key, "name") {
					goto simdjsonField2
				}
				if strings.EqualFold(key, "message") {
					goto simdjsonField3
				}
				if strings.EqualFold(key, "scores") {
					goto simdjsonField4
				}
				if strings.EqualFold(key, "number") {
					goto simdjsonField5
				}
			}
			if err := cursor.Unknown("Record", key); err != nil {
				return err
			}
			continue
		}
	simdjsonField0:
		{
			if err := cursor.Int(&dst.ID); err != nil {
				return err
			}
		}
		continue
	simdjsonField1:
		{
			if err := cursor.Bool(&dst.Active); err != nil {
				return err
			}
		}
		continue
	simdjsonField2:
		{
			if err := cursor.String(&dst.Name); err != nil {
				return err
			}
		}
		continue
	simdjsonField3:
		{
			if err := cursor.String(&dst.Message); err != nil {
				return err
			}
		}
		continue
	simdjsonField4:
		{
			null26, err26 := cursor.TryNull()
			if err26 != nil {
				return err26
			}
			var zero26 [3]Score
			dst.Scores = zero26
			if !null26 {
				if err := cursor.BeginArray("[3]Score"); err != nil {
					return err
				}
				for index26, first26 := 0, true; ; index26, first26 = index26+1, false {
					more26, err26 := cursor.NextArrayElement(first26)
					if err26 != nil {
						return err26
					}
					if !more26 {
						break
					}
					if index26 < len(dst.Scores) {
						if err := cursor.Float(&dst.Scores[index26]); err != nil {
							return err
						}
					} else if err := cursor.Skip(); err != nil {
						return err
					}
				}
			}
		}
		continue
	simdjsonField5:
		{
			if err := cursor.Number(&dst.Number); err != nil {
				return err
			}
		}
		continue
	}
}
