// Command simdjsongen generates concrete, interface-free JSON decoders for Go structs.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

const simdjsonImportPath = "github.com/thesyncim/simdjson"

func main() {
	typesFlag := flag.String("type", "", "comma-separated root struct type names")
	output := flag.String("output", "", "generated Go file")
	flag.Parse()
	if *typesFlag == "" {
		fatalf("-type is required")
	}

	roots := splitNames(*typesFlag)
	if *output == "" {
		*output = strings.ToLower(strings.Join(roots, "_")) + "_simdjson.go"
	}
	g, err := loadGenerator(*output)
	if err != nil {
		fatalf("%v", err)
	}
	generated, err := g.generate(roots)
	if err != nil {
		fatalf("%v", err)
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fatalf("write %s: %v", *output, err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "simdjsongen: "+format+"\n", args...)
	os.Exit(1)
}

func splitNames(text string) []string {
	var names []string
	for _, name := range strings.Split(text, ",") {
		if name = strings.TrimSpace(name); name != "" {
			names = append(names, name)
		}
	}
	return names
}

type generator struct {
	fset      *token.FileSet
	pkg       string
	specs     map[string]*ast.TypeSpec
	buf       strings.Builder
	counter   int
	needed    []string
	scheduled map[string]bool
	emitted   map[string]bool
}

func loadGenerator(output string) (*generator, error) {
	fset := token.NewFileSet()
	outputBase := filepath.Base(output)
	packages, err := parser.ParseDir(fset, ".", func(info os.FileInfo) bool {
		name := info.Name()
		return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go") && name != outputBase
	}, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	if len(packages) != 1 {
		return nil, fmt.Errorf("expected one package in current directory, found %d", len(packages))
	}
	var pkg *ast.Package
	for _, candidate := range packages {
		pkg = candidate
	}
	specs := make(map[string]*ast.TypeSpec)
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, raw := range gen.Specs {
				spec := raw.(*ast.TypeSpec)
				specs[spec.Name.Name] = spec
			}
		}
	}
	return &generator{
		fset:      fset,
		pkg:       pkg.Name,
		specs:     specs,
		scheduled: make(map[string]bool),
		emitted:   make(map[string]bool),
	}, nil
}

func (g *generator) generate(roots []string) ([]byte, error) {
	for _, root := range roots {
		if _, err := g.structType(root); err != nil {
			return nil, err
		}
		g.schedule(root)
	}

	g.line("// Code generated by simdjsongen; DO NOT EDIT.")
	g.line("")
	g.line("package " + g.pkg)
	g.line("")
	g.line("import (")
	g.line("\t\"strings\"")
	g.line("")
	g.line("\tsimdjson \"" + simdjsonImportPath + "\"")
	g.line(")")
	g.line("")
	g.line("var _ = strings.EqualFold")
	g.line("")

	for _, root := range roots {
		g.emitDecoder(root)
	}
	for len(g.needed) > 0 {
		name := g.needed[0]
		g.needed = g.needed[1:]
		if g.emitted[name] {
			continue
		}
		if err := g.emitStruct(name); err != nil {
			return nil, err
		}
		g.emitted[name] = true
	}

	source, err := format.Source([]byte(g.buf.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, g.buf.String())
	}
	return source, nil
}

func (g *generator) emitDecoder(name string) {
	decoder := name + "JSONDecoder"
	g.line("// " + decoder + " is a concrete generated decoder for " + name + ".")
	g.line("type " + decoder + " struct {")
	g.line("\tOptions simdjson.TypedOptions")
	g.line("}")
	g.line("")
	g.line("func (decoder " + decoder + ") Decode(src []byte, dst *" + name + ") error {")
	g.line("\tif dst == nil {")
	g.line("\t\treturn &simdjson.TypedDecodeError{TypeName: " + strconv.Quote(name) + ", Reason: \"destination is nil\"}")
	g.line("\t}")
	g.line("\tcursor := simdjson.NewDecoderCursor(src, decoder.Options)")
	g.line("\tif err := simdjsonDecode" + name + "(&cursor, dst); err != nil {")
	g.line("\t\treturn err")
	g.line("\t}")
	g.line("\treturn cursor.Finish()")
	g.line("}")
	g.line("")

	g.line("func (decoder " + decoder + ") DecodeArray(src []byte, dst []" + name + ") ([]" + name + ", error) {")
	g.line("\tcursor := simdjson.NewDecoderCursor(src, decoder.Options)")
	g.line("\tnull, err := cursor.TryNull()")
	g.line("\tif err != nil {")
	g.line("\t\treturn dst, err")
	g.line("\t}")
	g.line("\tif null {")
	g.line("\t\treturn nil, cursor.Finish()")
	g.line("\t}")
	g.line("\tif err := cursor.BeginArray(" + strconv.Quote("[]"+name) + "); err != nil {")
	g.line("\t\treturn dst, err")
	g.line("\t}")
	g.line("\tif dst == nil {")
	g.line("\t\tdst = make([]" + name + ", 0)")
	g.line("\t}")
	g.line("\tdst = dst[:0]")
	g.line("\tfor first := true; ; first = false {")
	g.line("\t\tmore, err := cursor.NextArrayElement(first)")
	g.line("\t\tif err != nil {")
	g.line("\t\t\treturn dst, err")
	g.line("\t\t}")
	g.line("\t\tif !more {")
	g.line("\t\t\tbreak")
	g.line("\t\t}")
	g.line("\t\tif first {")
	g.line("\t\t\tcursor.ReserveSlice(&dst, 128)")
	g.line("\t\t}")
	g.line("\t\tindex := len(dst)")
	g.line("\t\tif index < cap(dst) {")
	g.line("\t\t\tdst = dst[:index+1]")
	g.line("\t\t} else {")
	g.line("\t\t\tvar zero " + name)
	g.line("\t\t\tdst = append(dst, zero)")
	g.line("\t\t}")
	g.line("\t\tif err := simdjsonDecode" + name + "(&cursor, &dst[index]); err != nil {")
	g.line("\t\t\treturn dst, err")
	g.line("\t\t}")
	g.line("\t}")
	g.line("\treturn dst, cursor.Finish()")
	g.line("}")
	g.line("")
}

func (g *generator) emitStruct(name string) error {
	structType, err := g.structType(name)
	if err != nil {
		return err
	}
	fields, err := g.fields(structType)
	if err != nil {
		return fmt.Errorf("%s: %w", name, err)
	}

	g.line("func simdjsonReset" + name + "(dst *" + name + ") {")
	for _, field := range fields {
		if err := g.emitReset("dst."+field.goName, field.typ, "\t"); err != nil {
			return fmt.Errorf("%s.%s: %w", name, field.goName, err)
		}
	}
	g.line("}")
	g.line("")

	g.line("func simdjsonDecode" + name + "(cursor *simdjson.DecoderCursor, dst *" + name + ") error {")
	g.line("\tnull, err := cursor.TryNull()")
	g.line("\tif err != nil {")
	g.line("\t\treturn err")
	g.line("\t}")
	g.line("\tsimdjsonReset" + name + "(dst)")
	g.line("\tif null {")
	g.line("\t\treturn nil")
	g.line("\t}")
	g.line("\tif err := cursor.BeginObject(" + strconv.Quote(name) + "); err != nil {")
	g.line("\t\treturn err")
	g.line("\t}")
	g.line("\tfor first := true; ; first = false {")
	g.line("\t\tkey, ok, err := cursor.NextObjectField(first)")
	g.line("\t\tif err != nil {")
	g.line("\t\t\treturn err")
	g.line("\t\t}")
	g.line("\t\tif !ok {")
	g.line("\t\t\treturn nil")
	g.line("\t\t}")
	g.line("\t\tswitch key {")
	for index, field := range fields {
		g.line("\t\tcase " + strconv.Quote(field.jsonName) + ":")
		g.line("\t\t\tgoto simdjsonField" + strconv.Itoa(index))
	}
	g.line("\t\tdefault:")
	g.line("\t\t\tif !cursor.CaseSensitive() {")
	for index, field := range fields {
		g.line("\t\t\t\tif strings.EqualFold(key, " + strconv.Quote(field.jsonName) + ") {")
		g.line("\t\t\t\t\tgoto simdjsonField" + strconv.Itoa(index))
		g.line("\t\t\t\t}")
	}
	g.line("\t\t\t}")
	g.line("\t\t\tif err := cursor.Unknown(" + strconv.Quote(name) + ", key); err != nil {")
	g.line("\t\t\t\treturn err")
	g.line("\t\t\t}")
	g.line("\t\t\tcontinue")
	g.line("\t\t}")
	for index, field := range fields {
		g.line("\t\tsimdjsonField" + strconv.Itoa(index) + ":")
		g.line("\t\t{")
		if err := g.emitDecode("dst."+field.goName, field.typ, "\t\t\t"); err != nil {
			return fmt.Errorf("%s.%s: %w", name, field.goName, err)
		}
		g.line("\t\t}")
		g.line("\t\tcontinue")
	}
	g.line("\t}")
	g.line("}")
	g.line("")
	return nil
}

type generatedField struct {
	goName   string
	jsonName string
	typ      ast.Expr
}

func (g *generator) fields(structType *ast.StructType) ([]generatedField, error) {
	var fields []generatedField
	seen := make(map[string]bool)
	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			return nil, fmt.Errorf("anonymous fields are not supported; add an explicit JSON field")
		}
		tag := reflect.StructTag("")
		if field.Tag != nil {
			text, err := strconv.Unquote(field.Tag.Value)
			if err != nil {
				return nil, err
			}
			tag = reflect.StructTag(text)
		}
		jsonTag, tagged := tag.Lookup("json")
		for _, fieldName := range field.Names {
			if !fieldName.IsExported() {
				continue
			}
			jsonName := fieldName.Name
			if tagged {
				jsonName, _, _ = strings.Cut(jsonTag, ",")
				if jsonName == "-" {
					continue
				}
				if jsonName == "" {
					jsonName = fieldName.Name
				}
			}
			if seen[jsonName] {
				return nil, fmt.Errorf("duplicate JSON field name %q", jsonName)
			}
			seen[jsonName] = true
			fields = append(fields, generatedField{goName: fieldName.Name, jsonName: jsonName, typ: field.Type})
		}
	}
	return fields, nil
}

func (g *generator) emitDecode(expr string, typ ast.Expr, indent string) error {
	switch value := typ.(type) {
	case *ast.Ident:
		if method := scalarMethod(value.Name); method != "" {
			g.line(indent + "if err := cursor." + method + "(&" + expr + "); err != nil {")
			g.line(indent + "\treturn err")
			g.line(indent + "}")
			return nil
		}
		spec := g.specs[value.Name]
		if spec == nil {
			return fmt.Errorf("unknown named type %s", value.Name)
		}
		if spec.TypeParams != nil {
			return fmt.Errorf("generic named type %s is not supported", value.Name)
		}
		if _, ok := spec.Type.(*ast.StructType); ok {
			g.schedule(value.Name)
			g.line(indent + "if err := simdjsonDecode" + value.Name + "(cursor, &" + expr + "); err != nil {")
			g.line(indent + "\treturn err")
			g.line(indent + "}")
			return nil
		}
		return g.emitDecode(expr, spec.Type, indent)
	case *ast.SelectorExpr:
		if value.Sel.Name == "Number" {
			g.line(indent + "if err := cursor.Number(&" + expr + "); err != nil {")
			g.line(indent + "\treturn err")
			g.line(indent + "}")
			return nil
		}
		return fmt.Errorf("selector type %s is not supported", g.typeText(typ))
	case *ast.StarExpr:
		id := g.nextID()
		g.line(indent + "null" + id + ", err" + id + " := cursor.TryNull()")
		g.line(indent + "if err" + id + " != nil {")
		g.line(indent + "\treturn err" + id)
		g.line(indent + "}")
		g.line(indent + "if null" + id + " {")
		g.line(indent + "\t" + expr + " = nil")
		g.line(indent + "} else {")
		g.line(indent + "\tif " + expr + " == nil {")
		g.line(indent + "\t\t" + expr + " = new(" + g.typeText(value.X) + ")")
		g.line(indent + "\t}")
		if err := g.emitDecode("*("+expr+")", value.X, indent+"\t"); err != nil {
			return err
		}
		g.line(indent + "}")
		return nil
	case *ast.ArrayType:
		if value.Len == nil {
			return g.emitSlice(expr, value, indent)
		}
		return g.emitArray(expr, value, indent)
	case *ast.StructType:
		return fmt.Errorf("anonymous struct type %s is not supported", g.typeText(typ))
	default:
		return fmt.Errorf("type %s is not supported", g.typeText(typ))
	}
}

func (g *generator) emitSlice(expr string, typ *ast.ArrayType, indent string) error {
	id := g.nextID()
	typeName := g.typeText(typ)
	elemName := g.typeText(typ.Elt)
	g.line(indent + "null" + id + ", err" + id + " := cursor.TryNull()")
	g.line(indent + "if err" + id + " != nil {")
	g.line(indent + "\treturn err" + id)
	g.line(indent + "}")
	g.line(indent + "if null" + id + " {")
	g.line(indent + "\t" + expr + " = nil")
	g.line(indent + "} else {")
	g.line(indent + "\tif err := cursor.BeginArray(" + strconv.Quote(typeName) + "); err != nil {")
	g.line(indent + "\t\treturn err")
	g.line(indent + "\t}")
	g.line(indent + "\tif " + expr + " == nil {")
	g.line(indent + "\t\t" + expr + " = make(" + typeName + ", 0)")
	g.line(indent + "\t}")
	g.line(indent + "\t" + expr + " = " + expr + "[:0]")
	g.line(indent + "\tfor first" + id + " := true; ; first" + id + " = false {")
	g.line(indent + "\t\tmore" + id + ", err" + id + " := cursor.NextArrayElement(first" + id + ")")
	g.line(indent + "\t\tif err" + id + " != nil {")
	g.line(indent + "\t\t\treturn err" + id)
	g.line(indent + "\t\t}")
	g.line(indent + "\t\tif !more" + id + " {")
	g.line(indent + "\t\t\tbreak")
	g.line(indent + "\t\t}")
	g.line(indent + "\t\tif first" + id + " {")
	g.line(indent + "\t\t\tcursor.ReserveSlice(&" + expr + ", " + strconv.Itoa(g.elementJSONWidth(typ.Elt)) + ")")
	g.line(indent + "\t\t}")
	g.line(indent + "\t\tindex" + id + " := len(" + expr + ")")
	g.line(indent + "\t\tif index" + id + " < cap(" + expr + ") {")
	g.line(indent + "\t\t\t" + expr + " = " + expr + "[:index" + id + "+1]")
	g.line(indent + "\t\t} else {")
	g.line(indent + "\t\t\tvar zero" + id + " " + elemName)
	g.line(indent + "\t\t\t" + expr + " = append(" + expr + ", zero" + id + ")")
	g.line(indent + "\t\t}")
	if err := g.emitDecode(expr+"[index"+id+"]", typ.Elt, indent+"\t\t"); err != nil {
		return err
	}
	g.line(indent + "\t}")
	g.line(indent + "}")
	return nil
}

func (g *generator) emitArray(expr string, typ *ast.ArrayType, indent string) error {
	id := g.nextID()
	typeName := g.typeText(typ)
	g.line(indent + "null" + id + ", err" + id + " := cursor.TryNull()")
	g.line(indent + "if err" + id + " != nil {")
	g.line(indent + "\treturn err" + id)
	g.line(indent + "}")
	g.line(indent + "var zero" + id + " " + typeName)
	g.line(indent + expr + " = zero" + id)
	g.line(indent + "if !null" + id + " {")
	g.line(indent + "\tif err := cursor.BeginArray(" + strconv.Quote(typeName) + "); err != nil {")
	g.line(indent + "\t\treturn err")
	g.line(indent + "\t}")
	g.line(indent + "\tfor index" + id + ", first" + id + " := 0, true; ; index" + id + ", first" + id + " = index" + id + "+1, false {")
	g.line(indent + "\t\tmore" + id + ", err" + id + " := cursor.NextArrayElement(first" + id + ")")
	g.line(indent + "\t\tif err" + id + " != nil {")
	g.line(indent + "\t\t\treturn err" + id)
	g.line(indent + "\t\t}")
	g.line(indent + "\t\tif !more" + id + " {")
	g.line(indent + "\t\t\tbreak")
	g.line(indent + "\t\t}")
	g.line(indent + "\t\tif index" + id + " < len(" + expr + ") {")
	if err := g.emitDecode(expr+"[index"+id+"]", typ.Elt, indent+"\t\t\t"); err != nil {
		return err
	}
	g.line(indent + "\t\t} else if err := cursor.Skip(); err != nil {")
	g.line(indent + "\t\t\treturn err")
	g.line(indent + "\t\t}")
	g.line(indent + "\t}")
	g.line(indent + "}")
	return nil
}

func (g *generator) emitReset(expr string, typ ast.Expr, indent string) error {
	switch value := typ.(type) {
	case *ast.Ident:
		spec := g.specs[value.Name]
		if spec != nil {
			if _, ok := spec.Type.(*ast.StructType); ok {
				g.schedule(value.Name)
				g.line(indent + "simdjsonReset" + value.Name + "(&" + expr + ")")
				return nil
			}
			return g.emitReset(expr, spec.Type, indent)
		}
	case *ast.ArrayType:
		if value.Len == nil {
			g.line(indent + expr + " = " + expr + "[:0]")
			return nil
		}
	case *ast.StarExpr:
		g.line(indent + expr + " = nil")
		return nil
	case *ast.SelectorExpr:
		if value.Sel.Name == "Number" {
			g.line(indent + expr + " = \"\"")
			return nil
		}
	}
	id := g.nextID()
	g.line(indent + "var zero" + id + " " + g.typeText(typ))
	g.line(indent + expr + " = zero" + id)
	return nil
}

func scalarMethod(name string) string {
	switch name {
	case "bool":
		return "Bool"
	case "string":
		return "String"
	case "int", "int8", "int16", "int32", "int64":
		return "Int"
	case "uint", "uint8", "uint16", "uint32", "uint64", "uintptr":
		return "Uint"
	case "float32", "float64":
		return "Float"
	default:
		return ""
	}
}

func (g *generator) elementJSONWidth(expr ast.Expr) int {
	switch value := expr.(type) {
	case *ast.Ident:
		if scalarMethod(value.Name) != "" {
			if value.Name == "string" {
				return 32
			}
			return 16
		}
		if spec := g.specs[value.Name]; spec != nil {
			if _, ok := spec.Type.(*ast.StructType); ok {
				return 128
			}
			return g.elementJSONWidth(spec.Type)
		}
	case *ast.StarExpr:
		return g.elementJSONWidth(value.X)
	case *ast.ArrayType:
		return 64
	case *ast.StructType:
		return 128
	}
	return 32
}

func (g *generator) structType(name string) (*ast.StructType, error) {
	spec := g.specs[name]
	if spec == nil {
		return nil, fmt.Errorf("type %s not found", name)
	}
	if spec.TypeParams != nil {
		return nil, fmt.Errorf("generic root type %s is not supported", name)
	}
	structType, ok := spec.Type.(*ast.StructType)
	if !ok {
		return nil, fmt.Errorf("type %s is not a struct", name)
	}
	return structType, nil
}

func (g *generator) schedule(name string) {
	if !g.scheduled[name] {
		g.scheduled[name] = true
		g.needed = append(g.needed, name)
		sort.Strings(g.needed)
	}
}

func (g *generator) nextID() string {
	g.counter++
	return strconv.Itoa(g.counter)
}

func (g *generator) typeText(expr ast.Expr) string {
	var out bytes.Buffer
	if err := format.Node(&out, g.fset, expr); err != nil {
		panic(err)
	}
	return out.String()
}

func (g *generator) line(text string) {
	g.buf.WriteString(text)
	g.buf.WriteByte('\n')
}
